params:
  cuda_devices: []

optional_plugin_components: {}

shard_descriptor:
  template: shard_descriptor.ChestShardDescriptor
  params:
    data_folder: chest-xray-pneumonia
    rank_worldsize: 2,2 #envoy number X, total envoys
